### ISSUE TITLE
Can't seem to get any version of Quant CLI to perform any action

### ISSUE THREAD

**Issue by FleetAdmiralButter** [quantcdn/quant-cli#264]
**Describe the bug**
I've just re-installed the Quant CLI to deploy a project I haven't worked on in a while but for some reason the CLI exits immediately with no output when I try to run any commands. I've tried versions 3.0.0, 2.1.0, and 2.0.0 but they all exhibit the same behavior.

Trying to init a new project, no quant.json file is created:
```
➜ quant init
➜ echo $?
0
➜ ls -la
.  ..
```

Trying to deploy an existing Hugo project with a valid quant.json:
```
➜ quant deploy public
➜ quant deploy public --force
➜ echo $?
0
```

There's no output and no updated assets are pushed to QuantCDN.

**To Reproduce**
1. Install the latest version of the Quant CLI using `npm i -g @quantcdn/quant-cli`
2. Try to run any commands.

**Expected behavior**
Quant CLI inits/deploy normally.

**Screenshots**
<img width="410" alt="image" src="https://github.com/user-attachments/assets/d52a1b45-5ba2-4c02-a0c8-9e7ef89e9f22">

**Desktop (please complete the following information):**
 - OS: macOS 14.6, NodeJS 22.5.1

**Comment by kepol** [comment]
Thanks for testing this. I'll sync with the team and we'll try to debug asap.

**Comment by stooit** [comment]
@FleetAdmiralButter I've managed to replicate this, it's a little odd -- the dependencies aren't getting installed properly via the global install.

If you run an `npm i` in `/usr/local/lib/node_modules/@quantcdn/quant-cli` manually for now it should resolve. Will look at a structural fix asap, thanks for reporting!

**Comment by seathasky** [comment]
I'm friend of Fleet's and also another person having this issue.
![Screenshot 2024-08-06 at 4 16 52 AM](https://github.com/user-attachments/assets/ada9a712-f90e-4424-867a-8779f3f9e37c)
I've tried to cd to the directory you mentioned but get the following.

**Comment by stooit** [comment]
@seathasky sorry, that workaround wasn't very platform agnostic -- was just the default node dir for macos.

If you run `which quant` you'll find the node home directory, e.g on debian using nvm: `/home/stuart/.nvm/versions/node/v20.16.0/bin/quant`

In this example I need to run `npm i` inside `~/.nvm/versions/node/v20.16.0/lib/node_modules/@quantcdn/quant-cli`

We will have this structurally fixed in an upcoming release, apologies for the trouble!

**Comment by seathasky** [comment]
> @seathasky sorry, that workaround wasn't very platform agnostic -- was just the default node dir for macos.
> 
> If you run `which quant` you'll find the node home directory, e.g on debian using nvm: `/home/stuart/.nvm/versions/node/v20.16.0/bin/quant`
> 
> In this example I need to run `npm i` inside `~/.nvm/versions/node/v20.16.0/lib/node_modules/@quantcdn/quant-cli`
> 
> We will have this structurally fixed in an upcoming release, apologies for the trouble!

Thank you for the fast response. I was able to find the directory but am still getting errors running quant after doing what you requested:

![Screenshot 2024-08-06 at 4 56 22 AM](https://github.com/user-attachments/assets/5a8a9f56-990e-492a-9c74-d5a8c99c11c9)

**Comment by stooit** [comment]
@seathasky I imagine you're running Node v22 which we haven't added support for yet. That deprecation warning is actually something you can ignore for now (just press enter) and you'll be able to enter the rest of the init values.

We'll sort v22 support at the same time we resolve the issue with dependencies not getting installed properly on global installs.

**Comment by seathasky** [comment]
> @seathasky I imagine you're running Node v22 which we haven't added support for yet. That deprecation warning is actually something you can ignore for now (just press enter) and you'll be able to enter the rest of the init values.
> 
> We'll sort v22 support at the same time we resolve the issue with dependencies not getting installed properly on global installs.

**My hero!** 

Ty so much! This has solved my issue! You can close this now!
