### ISSUE TITLE
`unpublish` returns an err on success

### ISSUE THREAD

**Issue by stooit** [quantcdn/quant-cli#60]
**Describe the bug**
When running a `quant unpublish` the command exits with an error, even though the unpublish is successful

**To Reproduce**
1. Run `quant unpublish /content`
2. Result: `Error: ReferenceError: url is not defined`

**Expected behavior**
A success message

**Comment by steveworley** [comment]
This has been resolved with the latest release of the cli tool:

```
$ node cli.js unpublish /test
*** Quant unpublish ***
Success: Unpublished successfully
$ node cli.js unpublish /test
*** Quant unpublish ***
Error: Error: Resource is already unpublished.
$ node cli.js unpublish /test-2
*** Quant unpublish ***
Success: Unpublished successfully
```
